all:
  vars:
    ansible_user: devopsuser

  children:
    log_server:
      hosts:
        node1:
          ansible_host: 192.168.172.11  

    log_clients:
      hosts:
        node2:
          ansible_host: 192.168.172.12  
